spring.application.name=reservation-salles

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/reservation_salles
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8081
JWT_SECRET=ma_clef_secrete_super_longue_pour_hs256_123456
JWT_EXPIRATION=3600000
